### ISSUE TITLE
如何清空网络请求和console日志

### ISSUE THREAD

**Issue by huangang** [ihtml5/mdebug#29]
现在的network和console没有清空功能，请求和日志多的时候要看很久，很不方便

**Comment by ihtml5** [comment]
感谢反馈, 上周我们刚刚增加了console.clear方法, 清空功能我们近期开发下, 也欢迎你直接贡献代码. Thank you for your feedback. Last week we just added the console.clear method. We have recently developed the clear function. You are also welcome to contribute code directly.
